/**:
  ros__parameters:
    joy_type: XBOX
    update_rate: 30.0
    accel_ratio: 10.0
    brake_ratio: 10.0
    steer_ratio: 0.5  # overwritten by vehicle info
    steering_angle_velocity: 1.0
    accel_sensitivity: 1.0
    brake_sensitivity: 1.0
    control_command:
      raw_control: true
      velocity_gain: 1.54
      max_forward_velocity: 15.4
      max_backward_velocity: 15.4
      backward_accel_ratio: 10.0
